networks:
  idmaker-dole:

services:
  app:
    container_name: idmaker_app
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
    entrypoint: 
    networks:
      - idmaker-dole

  mysql:
    image: mysql:8.0
    container_name: idmaker_db
    ports:
      - 3306:3306
    volumes:
      - ./.docker/.docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: idtest
    networks:
      - idmaker-dole

volumes:
  db-data: